### PR TITLE
add some helper commands

### PR DESCRIPTION
**Pull request by afg984**
#1

### CODE REVIEW

**Comment by 2016rshah** [comment]
Looks good to me!

**Comment by afg984** [comment]
I just came up with this

```python
def move(self, forward=0, backward=0, left=0, right=0, up=0, down=0, cw=0, ccw=0)
    self._move(roll=right-left, pitch=backward-forward, gaz=up-down, yaw=cw-ccw)
```

does it seem any better?

**Comment by 2016rshah** [comment]
Although this is more concise in terms of code, I think it is slightly less user friendly. Especially because, in my opinion, functions should only do one thing, and this function does a ton of different versions of the same thing. In my opinion it would be better to split it up. Plus in documentation, it would be more clear to have different functions for moving different ways, as opposed to having a ton of documentation on just one function.

**Comment by afg984** [comment]
The main point for the second version is that it allows me to move up and forward at the same time.

**Comment by afg984** [comment]
#7 created for the other version.

**Comment by 2016rshah** [comment]
Oh I actually had not considered that! I would say that is a really good idea, I agree with you now

**Comment by afg984** [comment]
Glad we have consensus on it, thank you for helping out!

I'll be pushing the other one to pypi ASAP.

**Pull request closed without merging**
